const chatResponses = {
  // Navigation & General
  'help': 'I can help you with over 20 calculators! Try asking me about health (like BMI, TDEE), finance (like EMI, ROI), or utilities (like Age, GPA).',
  'how to use': 'Navigate to the "Calculators" page from the menu, select your preferred tool from the grid, enter your specifics, and hit calculate for instant results!',
  'theme': 'You can change the theme by clicking the Sun/Moon icon in the navigation bar. AuraCalc supports Dark, Light, and System modes seamlessly.',
  'dark mode': 'To activate dark mode, simply click the Moon icon on the top right corner of the navigation bar.',
  'save': 'For your maximum privacy, all calculations happen instantly in your browser and are NEVER saved or sent to any servers.',
  'privacy': 'AuraCalc is 100% private. We don\'t track your financial or health data. Everything is cleared the moment you refresh!',
  'offline': 'As of v2.0, AuraCalc requires an initial connection to load, but most math logic will run locally without internet.',
  'accuracy': 'All formulas used in AuraCalc (such as BMR or compound interest) use standard, academically verified calculations. However, always consult professionals for critical health/finance decisions.',
  'mobile': 'AuraCalc is fully responsive and optimized to feel just like a native app on your phone or tablet.',
  'contact': 'Have feedback or a bug to report? Head over to the Contact page via the menu to shoot us a message directly!',

  // Greetings
  'hi': 'Hello there! 👋 I\'m AuraBot, your calculation assistant. What can I help you figure out today?',
  'hello': 'Hey! 😊 Need help finding a calculator or understanding an equation?',
  'hey': 'Hey there! 👋 Ready to crunch some numbers?',
  'good morning': 'Good morning! ☀️ Need help with any calculations today?',
  'good afternoon': 'Good afternoon! 🌤️ How can I assist you with calculations?',
  'good evening': 'Good evening! 🌙 Need help with any calculations?',
  'good night': 'Good night! 😴 Need help with any calculations?',
  'how are you': 'I\'m doing great! Ready to help you with any calculations you need.',
  'what is your name': 'I am AuraBot, the AI assistant built specifically for AuraCalc v2.0 by Jaanvi Chouhan! I know everything about our 20+ calculators.',
  'who made you': 'I am AuraBot, the AI assistant built specifically for AuraCalc v2.0 by Jaanvi Chouhan! I know everything about our 20+ calculators.',
  'who created you': 'I am AuraBot, the AI assistant built specifically for AuraCalc v2.0 by Jaanvi Chouhan! I know everything about our 20+ calculators.',
  'who is jaanvi chouhan': 'Jaanvi Chouhan is the creator of AuraCalc v2.0, a premium calculation suite with over 50+ calculators and an AI assistant.',
  'thanks': 'You\'re welcome! I\'m always here if you need more help computing things!',
  'thank you': 'Happy to help! Let me know if you want to calculate anything else.',
  'who are you': 'I am AuraBot, the AI assistant built specifically for AuraCalc v2.0 by Jaanvi Chouhan! I know everything about our 20+ calculators.',

  // Conversational Handlers
  'yes': 'Awesome! Let me know what specific calculator you want to use next.',
  'no': 'No problem. Feel free to explore the platform—there are over 50 calculators here!',
  'i don\'t know': 'That\'s perfectly fine! Browse the "Calculators" tab—you can search by category if you aren\'t sure what you need.',
  'everything': 'AuraCalc v2.0 literally calculates EVERYTHING! From advanced engineering physics to basic health macros.',
  'i dont know': 'That\'s perfectly fine! Browse the "Calculators" tab—you can search by category if you aren\'t sure what you need.',
  'what can you do': 'I can guide you through our massive 50+ calculation suite! Ask me about Engineering, Finance, Tech, Construction, Math, or Health.',
  'okay': 'Great! Anything else I can help with?',
  'ok': 'Great! Anything else I can help with?',

  // Extended Categories
  'engineering': 'Our Engineering suite includes Force, Velocity, Acceleration, Ohm\'s Law, Power, Pressure, Density, and more.',
  'construction': 'Building something? We have calculators for Concrete Bags, Area, Paint Gallons, and Tile counts.',
  'education': 'In academics? Use our GPA, Grades, Attendance, and Study Time calculators.',
  'travel': 'Planning a trip? Compute Fuel Cost, vehicle Mileage, and precise Travel Time routing.',
  'technology': 'Tech tools include Binary converter, IP Subnetting, and Data Storage actual-size metrics.',
  'math': 'Mathematics includes Basic, Scientific, Fractions, Ratios, Averages, Standard Deviation, and Probability.',

  // 🧮 50+ Detailed Calculator Mappings
  'bmi': 'BMI (Body Mass Index) evaluates your body weight relative to your height. Simply enter your weight in kg and height in cm to see which health tier you fall into!',
  'pregnancy': 'The Pregnancy Due Date calculator adds 280 days (40 weeks) to your last menstrual period start date to give you an estimated delivery date! Consult your OB/GYN for official schedules.',
  'due date': 'To calculate your baby\'s due date, visit the Health section and enter the first day of your last period.',
  'protein': 'Protein needs depend on your weight and activity level. Sedentary people need less (~0.8g/kg), while active gym-goers need more (up to 1.6g-2g/kg). Our Protein Calculator figures this out for you!',
  'period': 'The Period Tracker predicts your next cycle. Just enter your last cycle start date and your average cycle length (typically 21-35 days).',
  'bmr': 'BMR (Basal Metabolic Rate) is the exact number of calories your body burns at complete rest just to keep you alive. We use the Mifflin-St Jeor equation internally!',
  'tdee': 'TDEE (Total Daily Energy Expenditure) multiplies your BMR by your physical activity level to tell you EXACTLY how many calories you burn per day. Perfect for bulking or cutting!',
  'water': 'Water Intake is vital! Our calculator recommends ~35ml of water per kg of body weight, plus extra depending on how active you are. Hydrate well!',
  'ideal weight': 'We use the famous Miller Formula to estimate your ideal body weight based on your height and biological gender.',

  // Finance
  'emi': 'Our Loan EMI Calculator computes your Equated Monthly Installment. You\'ll need the principal loan amount, annual interest rate, and how many months you plan to borrow for.',
  'loan': 'Taking out a loan? Use our EMI calculator to see exactly how much you\'ll be paying monthly, plus the total interest you\'ll accumulate over the tenure!',
  'roi': 'Want to know if an investment was worth it? The ROI (Return On Investment) calculator takes your final value and subtracts the initial cost to give you your percentage gain (or loss)!',
  'compound interest': 'Einstein called Compound Interest the 8th wonder of the world! Enter your principal, interest rate, duration, and compounding frequency (like annually or monthly) to see your wealth grow.',
  'simple interest': 'Calculates basic interest without compounding (PRT/100).',
  'sip': 'SIP Calculator computes the future value of your Mutual Fund monthly SIPs based on an expected annualized return.',
  'salary': 'The Salary Calculator takes your gross income and subtracts common deductions like Income Tax and PF to give you your precise net take-home pay.',
  'profit margin': 'Profit Margin Calculator helps businesses determine gross margins based on Cost Price and Revenue.',
  'gst': 'The GST (Goods and Services Tax) calculator helps you easily add specific tax slabs (like 5%, 12%, 18%, 28%) to your product prices.',
  'tax': 'We offer a GST calculator for product taxes, and a Salary Calculator to deduct income tax from gross pay!',
  'discount': 'The Discount Calculator tells you the final price of an item during a sale. Just enter the original price and the discount percentage (e.g., 20%).',
  'currency': 'The Currency Converter gives you real-time equivalent values between major global currencies like USD, INR, EUR, GBP, and JPY.',

  // Math & Engineering & Utility & Tech
  'basic': 'We have a standard math calculator for adding, subtracting, dividing, and multiplying.',
  'scientific': 'The Scientific Calculator lets you solve Trig functions (Sin, Cos, Tan) and Logarithms immediately.',
  'fraction': 'Add, subtract, multiply, or divide exact numerators and denominators without decimals blocking you.',
  'ratio': 'Solve for X in any A:B = C:D ratio.',
  'average': 'Find the mean average of any dataset instantly.',
  'standard deviation': 'Find the variance and standard deviation of any sample or population data.',
  'force': 'Physics: Force = Mass * Acceleration (Newton\'s second law).',
  'velocity': 'Physics: Compute Average Velocity given distance and time traveled.',
  'ohms law': 'Electrical: Compute Voltage (V), Current (I), or Resistance (R) seamlessly.',
  'power': 'Electrical: Power = Voltage * Current (Watts).',
  'pressure': 'Fluid: Compute Pressure (Pascals) based on area and force.',
  'density': 'Material physics: Compute Density based on Mass and Volume.',
  'concrete': 'Construction: Enter Slab dimensions to see exactly how many cubic yards or 80lb bags of concrete you need!',
  'paint': 'Construction: Calculates paint gallons based on wall surface area and number of coats.',
  'tile': 'Flooring: Given a room area and tile sizing, calculates exact tile count + 10% wastage overage.',
  'grade': 'Academic: Calculate weighted grades using multiple assignment values.',
  'attendance': 'Academic: Figure out exactly how your absences affect your percentage.',
  'fuel': 'Travel: Computes trip fuel costs using gas prices and vehicle mileage constraints.',
  'mileage': 'Travel: Computes vehicle distance-per-unit fuel efficiency.',
  'binary': 'Tech: Convert base-10 decimals quickly to Binary and Hexadecimal strings.',
  'subnet': 'Networking: Enter a CIDR notation (e.g. /24) to find the number of usable hosts.',
  'data storage': 'Tech: Ever wonder why your 1TB drive shows as 931GB? We convert Base-10 metric sizes to Base-2 binary OS sizes.',
  'random': 'Roll the dice! We have a Random Number Generator in the Misc section.',

  // Utility
  'age': 'Want to know exactly how old you are? Our Age calculator counts down your exact age in Years, Months, and Days based on your birthday!',
  'birthday': 'Use our Age calculator in the Utility tab to process your exact birthday metrics!',
  'percent': 'Our Percentage calculator makes fractions easy. Want to know what 15% of 850 is? It solves it instantly without you doing the algebra.',
  'unit': 'The Unit Converter seamlessly translates between Meters, Feet, Kilometers, and Miles. Great for quickly comparing distances or lengths!',
  'tip': 'At a restaurant? The Tip Calculator lets you split adding 10%, 15%, 18%, or 20% to your bill without doing mental math.',
  'gpa': 'The GPA Calculator averages out your academic grades (on a 4.0 scale) and lets you know exactly where your current semester stands.',
  'grade': 'Trying to track your academics? Check out the GPA Calculator under the Utility tab!'
};

export default chatResponses;
